language: python
sudo: false
dist: precise

cache:
  - bundler
  - pip

python:
  - 2.7
  - 3.5
  - 3.6
  - nightly
  - pypy
  # - pypy3

addons:
  apt:
    packages:
      - libpcap-dev
      - libsctp-dev
      - libncurses5-dev
      - libssl-dev
      - libgsl0-dev

install:
  - pip install -e .
  - pip install --upgrade pytest
  - pip list

before_script:
  - git clone https://github.com/SIPp/sipp.git
  - cd sipp
  - ./build.sh --full
  - export PATH="$PWD:$PATH"
  - cd ..

script:
  - pytest tests/
